### ISSUE TITLE
conda GDAL/RasterIO broken again

### ISSUE THREAD

**Issue by fmaussion** [OGGM/OGGM-Anaconda#1]
Hi have allowed myself to rebuild the Travis tests because we had some trouble on appveyor with master.

It is now confirmed that it is not platform specific... Importing rasterio fails with:

```
Traceback (most recent call last):
  File "/home/travis/build/OGGM/OGGM-Anaconda/output/test-tmp_dir/run_test.py", line 30, in <module>
    import oggm
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/oggm/__init__.py", line 10, in <module>
    from oggm.utils import GlacierDirectory, entity_task, divide_task
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/oggm/utils.py", line 43, in <module>
    from rasterio.tools.merge import merge as merge_tool
ImportError: No module named tools.merge
```

**Comment by fmaussion** [comment]
I've just submitted a report to the conda-forge guys: https://github.com/conda-forge/rasterio-feedstock/issues/5

**Comment by fmaussion** [comment]
Closed by: https://github.com/conda-forge/rasterio-feedstock/issues/5#event-641374589

I updated the docs and OGGM to use conda-forge as default: http://oggm.readthedocs.org/en/latest/installing-oggm.html#packages

**Comment by TimoRoth** [comment]
This is happening again, with a lot of different errors depending on the platform and python version:

https://travis-ci.org/OGGM/OGGM-Anaconda/builds/139761941

Maybe we should re-open the issue at conda-forge?

**Comment by fmaussion** [comment]
Yes, if this is confirmed on Monday feel free to open an issue on conda-forge. Thanks!
